version: "3.7"
services:
  app:
    command: /bin/bash -c "yarn && yarn dev"
    build: .
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    tty: true
    ports:
      - 3000:3000
volumes:
  node_modules:
